
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Aug 20 18:01:24 CEST 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MASMAS = 17;
  public static final int MENOSMENOS = 18;
  public static final int RNUM = 44;
  public static final int AC = 9;
  public static final int POR = 13;
  public static final int CASE = 23;
  public static final int INT = 40;
  public static final int FOR = 25;
  public static final int CP = 5;
  public static final int NOT = 33;
  public static final int AND = 32;
  public static final int LT = 34;
  public static final int OR = 31;
  public static final int DIV = 14;
  public static final int GEQ = 37;
  public static final int NUM = 43;
  public static final int CC = 10;
  public static final int IF = 20;
  public static final int EOF = 0;
  public static final int ASIG = 15;
  public static final int error = 1;
  public static final int COMA = 8;
  public static final int MENOS = 12;
  public static final int MOD = 19;
  public static final int NEQ = 39;
  public static final int IDENT = 42;
  public static final int BREAK = 24;
  public static final int EQ = 38;
  public static final int MENOSUNARIO = 16;
  public static final int CLL = 7;
  public static final int SWITCH = 22;
  public static final int ELSE = 21;
  public static final int TO = 28;
  public static final int WHILE = 26;
  public static final int FLOAT = 41;
  public static final int LEQ = 35;
  public static final int ALL = 6;
  public static final int DOWNTO = 29;
  public static final int GT = 36;
  public static final int AP = 4;
  public static final int PRINT = 2;
  public static final int DO = 27;
  public static final int STEP = 30;
  public static final int PYC = 3;
  public static final int MAS = 11;
}

