
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Sep 04 19:51:00 CEST 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MASMAS = 17;
  public static final int DIVEQ = 23;
  public static final int MENOSMENOS = 18;
  public static final int RNUM = 49;
  public static final int AC = 9;
  public static final int POR = 13;
  public static final int COMMENT = 46;
  public static final int CASE = 27;
  public static final int INT = 44;
  public static final int FOR = 29;
  public static final int CP = 5;
  public static final int NOT = 37;
  public static final int AND = 36;
  public static final int LT = 38;
  public static final int OR = 35;
  public static final int DIV = 14;
  public static final int GEQ = 41;
  public static final int NUM = 48;
  public static final int CC = 10;
  public static final int IF = 24;
  public static final int EOF = 0;
  public static final int ASIG = 15;
  public static final int error = 1;
  public static final int COMA = 8;
  public static final int MENOS = 12;
  public static final int MOD = 19;
  public static final int NEQ = 43;
  public static final int IDENT = 47;
  public static final int BREAK = 28;
  public static final int EQ = 42;
  public static final int MASEQ = 20;
  public static final int MENOSUNARIO = 16;
  public static final int CLL = 7;
  public static final int SWITCH = 26;
  public static final int POREQ = 22;
  public static final int ELSE = 25;
  public static final int TO = 32;
  public static final int WHILE = 30;
  public static final int FLOAT = 45;
  public static final int LEQ = 39;
  public static final int ALL = 6;
  public static final int DOWNTO = 33;
  public static final int MENOSEQ = 21;
  public static final int GT = 40;
  public static final int AP = 4;
  public static final int PRINT = 2;
  public static final int DO = 31;
  public static final int STEP = 34;
  public static final int PYC = 3;
  public static final int MAS = 11;
}

