
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Aug 06 18:22:27 CEST 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GEQ = 28;
  public static final int AND = 23;
  public static final int MENOS = 9;
  public static final int LT = 25;
  public static final int IDENT = 31;
  public static final int ELSE = 15;
  public static final int CP = 5;
  public static final int PYC = 3;
  public static final int OR = 22;
  public static final int WHILE = 20;
  public static final int ALL = 6;
  public static final int NOT = 24;
  public static final int CLL = 7;
  public static final int SWITCH = 16;
  public static final int IF = 14;
  public static final int GT = 27;
  public static final int POR = 10;
  public static final int AP = 4;
  public static final int NUM = 32;
  public static final int DO = 21;
  public static final int MENOSUNARIO = 13;
  public static final int EOF = 0;
  public static final int BREAK = 18;
  public static final int DIV = 11;
  public static final int CASE = 17;
  public static final int PRINT = 2;
  public static final int error = 1;
  public static final int EQ = 29;
  public static final int LEQ = 26;
  public static final int FOR = 19;
  public static final int NEQ = 30;
  public static final int ASIG = 12;
  public static final int MAS = 8;
}

