/* The following code was generated by JFlex 1.4.3 on 8/6/18 6:22 PM */

import java_cup.runtime.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 8/6/18 6:22 PM from the specification file
 * <tt>PLC.flex</tt>
 */
class Yylex implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\2\44\25\0\1\44\1\40\4\0\1\35\1\0\1\30\1\31"+
    "\1\4\1\2\1\0\1\3\1\0\1\5\1\42\11\43\1\0\1\27"+
    "\1\36\1\1\1\37\2\0\32\41\4\0\1\41\1\0\1\22\1\23"+
    "\1\21\1\17\1\10\1\7\1\41\1\16\1\6\1\41\1\24\1\11"+
    "\1\41\1\26\1\13\1\25\1\41\1\14\1\12\1\20\2\41\1\15"+
    "\3\41\1\32\1\34\1\33\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\12\7"+
    "\1\10\1\11\1\12\1\13\1\14\2\1\1\15\1\16"+
    "\1\17\2\20\1\21\1\22\1\23\4\7\1\24\3\7"+
    "\1\25\1\26\1\27\1\30\1\31\1\32\6\7\1\33"+
    "\2\7\1\34\3\7\1\35\1\36\1\37\1\40";

  private static int [] zzUnpackAction() {
    int [] result = new int[63];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\45\0\112\0\45\0\45\0\45\0\45\0\157"+
    "\0\224\0\271\0\336\0\u0103\0\u0128\0\u014d\0\u0172\0\u0197"+
    "\0\u01bc\0\45\0\45\0\45\0\45\0\45\0\u01e1\0\u0206"+
    "\0\u022b\0\u0250\0\u0275\0\45\0\u029a\0\45\0\45\0\336"+
    "\0\u02bf\0\u02e4\0\u0309\0\u032e\0\336\0\u0353\0\u0378\0\u039d"+
    "\0\45\0\45\0\45\0\45\0\45\0\336\0\u03c2\0\u03e7"+
    "\0\u040c\0\u0431\0\u0456\0\u047b\0\336\0\u04a0\0\u04c5\0\336"+
    "\0\u04ea\0\u050f\0\u0534\0\336\0\336\0\336\0\336";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[63];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\2\13\1\15\1\13\1\16\1\13"+
    "\1\17\1\13\1\20\1\13\1\21\1\13\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\1\30\1\31\1\32\1\33"+
    "\1\13\1\34\1\35\1\36\46\0\1\37\51\0\1\13"+
    "\1\40\17\13\12\0\3\13\7\0\5\13\1\41\13\13"+
    "\12\0\3\13\7\0\3\13\1\42\15\13\12\0\3\13"+
    "\7\0\21\13\12\0\3\13\7\0\7\13\1\43\11\13"+
    "\12\0\3\13\7\0\10\13\1\44\10\13\12\0\3\13"+
    "\7\0\5\13\1\45\13\13\12\0\3\13\7\0\14\13"+
    "\1\46\4\13\12\0\3\13\7\0\6\13\1\47\12\13"+
    "\12\0\3\13\7\0\6\13\1\50\12\13\12\0\3\13"+
    "\35\0\1\51\45\0\1\52\10\0\1\53\44\0\1\54"+
    "\44\0\1\55\105\0\2\35\7\0\6\13\1\56\12\13"+
    "\12\0\3\13\7\0\4\13\1\57\14\13\12\0\3\13"+
    "\7\0\1\60\20\13\12\0\3\13\7\0\1\61\20\13"+
    "\12\0\3\13\7\0\4\13\1\62\14\13\12\0\3\13"+
    "\7\0\2\13\1\63\16\13\12\0\3\13\7\0\1\64"+
    "\20\13\12\0\3\13\7\0\2\13\1\65\16\13\12\0"+
    "\3\13\7\0\12\13\1\66\6\13\12\0\3\13\7\0"+
    "\3\13\1\67\15\13\12\0\3\13\7\0\2\13\1\70"+
    "\16\13\12\0\3\13\7\0\14\13\1\71\4\13\12\0"+
    "\3\13\7\0\20\13\1\72\12\0\3\13\7\0\13\13"+
    "\1\73\5\13\12\0\3\13\7\0\2\13\1\74\16\13"+
    "\12\0\3\13\7\0\16\13\1\75\2\13\12\0\3\13"+
    "\7\0\12\13\1\76\6\13\12\0\3\13\7\0\10\13"+
    "\1\77\10\13\12\0\3\13\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[1369];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\4\11\12\1\5\11\5\1\1\11"+
    "\1\1\2\11\11\1\5\11\22\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[63];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Yylex(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Yylex(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 110) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 24: 
          { return new Symbol(sym.GEQ);
          }
        case 33: break;
        case 23: 
          { return new Symbol(sym.LEQ);
          }
        case 34: break;
        case 1: 
          { throw new Error("Argumento no reconocido <<"+yytext()+" >>");
          }
        case 35: break;
        case 4: 
          { return new Symbol(sym.MENOS);
          }
        case 36: break;
        case 19: 
          { return new Symbol(sym.IF);
          }
        case 37: break;
        case 3: 
          { return new Symbol(sym.MAS);
          }
        case 38: break;
        case 25: 
          { return new Symbol(sym.NEQ);
          }
        case 39: break;
        case 7: 
          { return new Symbol(sym.IDENT,yytext());
          }
        case 40: break;
        case 30: 
          { return new Symbol(sym.BREAK);
          }
        case 41: break;
        case 13: 
          { return new Symbol(sym.LT);
          }
        case 42: break;
        case 28: 
          { return new Symbol(sym.CASE);
          }
        case 43: break;
        case 20: 
          { return new Symbol(sym.DO);
          }
        case 44: break;
        case 27: 
          { return new Symbol(sym.ELSE);
          }
        case 45: break;
        case 26: 
          { return new Symbol(sym.FOR);
          }
        case 46: break;
        case 22: 
          { return new Symbol(sym.AND);
          }
        case 47: break;
        case 15: 
          { return new Symbol(sym.NOT);
          }
        case 48: break;
        case 32: 
          { return new Symbol(sym.SWITCH);
          }
        case 49: break;
        case 6: 
          { return new Symbol(sym.DIV);
          }
        case 50: break;
        case 9: 
          { return new Symbol(sym.AP);
          }
        case 51: break;
        case 29: 
          { return new Symbol(sym.WHILE);
          }
        case 52: break;
        case 11: 
          { return new Symbol(sym.ALL);
          }
        case 53: break;
        case 16: 
          { return new Symbol(sym.NUM,yytext());
          }
        case 54: break;
        case 5: 
          { return new Symbol(sym.POR);
          }
        case 55: break;
        case 17: 
          { ;
          }
        case 56: break;
        case 14: 
          { return new Symbol(sym.GT);
          }
        case 57: break;
        case 18: 
          { return new Symbol(sym.EQ);
          }
        case 58: break;
        case 21: 
          { return new Symbol(sym.OR);
          }
        case 59: break;
        case 8: 
          { return new Symbol(sym.PYC);
          }
        case 60: break;
        case 10: 
          { return new Symbol(sym.CP);
          }
        case 61: break;
        case 12: 
          { return new Symbol(sym.CLL);
          }
        case 62: break;
        case 31: 
          { return new Symbol(sym.PRINT);
          }
        case 63: break;
        case 2: 
          { return new Symbol(sym.ASIG);
          }
        case 64: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
