
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Sep 01 19:42:53 CEST 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GEQ = 25;
  public static final int MOD = 19;
  public static final int MENOS = 16;
  public static final int LT = 22;
  public static final int IDENT = 28;
  public static final int ELSE = 8;
  public static final int CP = 13;
  public static final int RANGE = 11;
  public static final int IN = 10;
  public static final int WHILE = 3;
  public static final int POT = 20;
  public static final int IF = 6;
  public static final int GT = 24;
  public static final int POR = 17;
  public static final int AP = 12;
  public static final int NUM = 29;
  public static final int DP = 5;
  public static final int COMA = 14;
  public static final int MENOSUNARIO = 21;
  public static final int EOF = 0;
  public static final int DIV = 18;
  public static final int ELIF = 7;
  public static final int PRINT = 2;
  public static final int error = 1;
  public static final int EQ = 26;
  public static final int LEQ = 23;
  public static final int FOR = 9;
  public static final int NEQ = 27;
  public static final int ASIG = 4;
  public static final int MAS = 15;
}

