
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Sep 03 17:15:48 CEST 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MASMAS = 18;
  public static final int DIVEQ = 24;
  public static final int MENOSMENOS = 19;
  public static final int RNUM = 60;
  public static final int AC = 9;
  public static final int CHAR = 53;
  public static final int POR = 14;
  public static final int COMMENT = 49;
  public static final int CASE = 28;
  public static final int INT = 47;
  public static final int FOR = 32;
  public static final int CHARACTER = 52;
  public static final int CP = 5;
  public static final int NOT = 40;
  public static final int AND = 39;
  public static final int LT = 41;
  public static final int CASTCHAR = 57;
  public static final int OR = 38;
  public static final int DIV = 15;
  public static final int GEQ = 44;
  public static final int NUM = 59;
  public static final int CC = 10;
  public static final int IF = 25;
  public static final int EOF = 0;
  public static final int AMP = 51;
  public static final int ASIG = 16;
  public static final int error = 1;
  public static final int COMA = 8;
  public static final int MENOS = 13;
  public static final int MOD = 20;
  public static final int NEQ = 46;
  public static final int ASK = 31;
  public static final int IDENT = 58;
  public static final int BREAK = 29;
  public static final int EQ = 45;
  public static final int MASEQ = 21;
  public static final int MENOSUNARIO = 17;
  public static final int CLL = 7;
  public static final int SWITCH = 27;
  public static final int ELVIS = 50;
  public static final int POREQ = 23;
  public static final int CASTINT = 55;
  public static final int ELSE = 26;
  public static final int CHANGECHAR = 54;
  public static final int TO = 35;
  public static final int WHILE = 33;
  public static final int DEFAULT = 30;
  public static final int FLOAT = 48;
  public static final int LEQ = 42;
  public static final int ALL = 6;
  public static final int DOWNTO = 36;
  public static final int MENOSEQ = 22;
  public static final int GT = 43;
  public static final int AP = 4;
  public static final int DP = 11;
  public static final int CASTFLOAT = 56;
  public static final int PRINT = 2;
  public static final int DO = 34;
  public static final int STEP = 37;
  public static final int PYC = 3;
  public static final int MAS = 12;
}

