
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Aug 13 19:57:25 CEST 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MASMAS = 15;
  public static final int MENOSMENOS = 16;
  public static final int POR = 11;
  public static final int CASE = 21;
  public static final int INT = 37;
  public static final int FOR = 23;
  public static final int CP = 5;
  public static final int NOT = 30;
  public static final int AND = 29;
  public static final int LT = 31;
  public static final int OR = 28;
  public static final int DIV = 12;
  public static final int GEQ = 34;
  public static final int NUM = 39;
  public static final int IF = 18;
  public static final int EOF = 0;
  public static final int ASIG = 13;
  public static final int error = 1;
  public static final int COMA = 8;
  public static final int MENOS = 10;
  public static final int MOD = 17;
  public static final int NEQ = 36;
  public static final int IDENT = 38;
  public static final int BREAK = 22;
  public static final int EQ = 35;
  public static final int MENOSUNARIO = 14;
  public static final int CLL = 7;
  public static final int SWITCH = 20;
  public static final int ELSE = 19;
  public static final int TO = 26;
  public static final int WHILE = 24;
  public static final int LEQ = 32;
  public static final int ALL = 6;
  public static final int DOWNTO = 27;
  public static final int AP = 4;
  public static final int GT = 33;
  public static final int PRINT = 2;
  public static final int DO = 25;
  public static final int PYC = 3;
  public static final int MAS = 9;
}

